//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OMRFinalEntities : DbContext
    {
        public OMRFinalEntities()
            : base("name=OMRFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblMarksEng> tblMarksEngs { get; set; }
        public virtual DbSet<tblRNBEng> tblRNBEngs { get; set; }
        public virtual DbSet<tblSchoolListEng> tblSchoolListEngs { get; set; }
        public virtual DbSet<tblStudentInfoEng> tblStudentInfoEngs { get; set; }
        public virtual DbSet<tblDistrictEng> tblDistrictEngs { get; set; }
        public virtual DbSet<tblTalukaEng> tblTalukaEngs { get; set; }
        public virtual DbSet<tblVillagesEng> tblVillagesEngs { get; set; }
        public virtual DbSet<tblStandardEng> tblStandardEngs { get; set; }
    }
}
