//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMarksEng
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string Barcode1 { get; set; }
        public string Barcode2 { get; set; }
        public int TalukaId { get; set; }
        public int correctAns1 { get; set; }
        public int correctAns2 { get; set; }
        public int Mark1 { get; set; }
        public int Mark2 { get; set; }
        public int Standard { get; set; }
        public int ExamNo { get; set; }
        public System.DateTime Birthday { get; set; }
        public int StateRank { get; set; }
        public int DistrictR { get; set; }
        public int SubDistR { get; set; }
        public int Year { get; set; }
        public Nullable<bool> Paper1Attendance { get; set; }
        public Nullable<bool> Paper2Attendance { get; set; }
    }
}
