//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRNBEng
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int RollNumber { get; set; }
        public int Barcode1 { get; set; }
        public int Barcode2 { get; set; }
        public int Barcode3 { get; set; }
        public int TalukaId { get; set; }
        public int KendraId { get; set; }
        public int StandardId { get; set; }
        public int YearId { get; set; }
    
        public virtual tblStandardEng tblStandardEng { get; set; }
    }
}
