//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentInfoEng
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public int SchoolId { get; set; }
        public int AgencyId { get; set; }
        public int Language { get; set; }
        public string SchoolTesacherPhoneNumber { get; set; }
        public string VillageName { get; set; }
        public int StandardId { get; set; }
        public string Amount { get; set; }
        public bool IsSelf { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public int DainikId { get; set; }
        public bool IsDainik { get; set; }
        public bool IsSemiEnglish { get; set; }
    
        public virtual tblSchoolListEng tblSchoolListEng { get; set; }
        public virtual tblStandardEng tblStandardEng { get; set; }
    }
}
