//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStandardEng
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStandardEng()
        {
            this.tblRNBEngs = new HashSet<tblRNBEng>();
            this.tblStudentInfoEngs = new HashSet<tblStudentInfoEng>();
        }
    
        public int ID { get; set; }
        public string Standard { get; set; }
        public string AmountStr { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRNBEng> tblRNBEngs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentInfoEng> tblStudentInfoEngs { get; set; }
    }
}
