//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchoolListEng
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSchoolListEng()
        {
            this.tblStudentInfoEngs = new HashSet<tblStudentInfoEng>();
        }
    
        public int Id { get; set; }
        public string SchoolName { get; set; }
        public int VillageId { get; set; }
        public int Group { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentInfoEng> tblStudentInfoEngs { get; set; }
        public virtual tblVillagesEng tblVillagesEng { get; set; }
    }
}
