//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVillagesEng
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVillagesEng()
        {
            this.tblSchoolListEngs = new HashSet<tblSchoolListEng>();
        }
    
        public int ID { get; set; }
        public int TalukaID { get; set; }
        public string VillageName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSchoolListEng> tblSchoolListEngs { get; set; }
        public virtual tblTalukaEng tblTalukaEng { get; set; }
    }
}
